# your server name
server-name: "§bServer§fHCF §7| §6Map 1"
# Your server description, explain what your server is about, WARNING: this will be used in the settings menu 
server-description: "A simple hcf core, i think"
# Your MOTD
server-motd: "MyServer - HCF"
# This is necessary, we cannot guarantee that your server will support a thousand simultaneous players, add limits to your ideas man
server-slots: 100
# Faction custom data
faction:
 max-allies: 0
 max-players: 1
# Provider
provider:
 database:
  name: sqlite3
  sqlite3: 
    file-name: "HCFData.db"
  mysql: 
    address: "127.0.0.1"
    port: 3306
    username: "root"
    pass: ""
    schema: "HCF"
 data:
  name: json