blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://discord.gg/PsKkJhNEkM
    about: Please ask and answer questions here.
  - name: Error de seguridad
    url: https://discord.gg/PsKkJhNEkM
    about: Please report security vulnerabilities here.