name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Do not forget to be respectful, we do not allow violent reactions, this will lead to the closure of your issue"
        pr-message: "Do not forget to be respectful, we do not allow violent reactions"
